version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:13.2-alpine
    volumes:
      - ./yard/data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - db
  
  redis:
    image: redis:alpine3.11 
  
  celery: #worker
    build: ./
    command: celery -A project_core worker -l info
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
  
  celery-beat: #Scheduler
    build: ./
    command: celery -A project_core beat -l info
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
