# Generated by Django 3.2.9 on 2021-11-18 11:01

from django.db import migrations, models
import shortener.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_url', models.CharField(max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(default=shortener.utils.default_expiry_time)),
                ('times_visited', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
